import { Toast, ToastKey } from "./index.types";

export const TOAST_MAP: { [K in ToastKey]: Toast } = {
  [ToastKey.Logout]: {
    priority: "high",
    title: "Authentication Logout",
    message: "Successfully logged out",
    type: "info",
    duration: 2000,
    isRemovableByClick: true,
  },
  [ToastKey.LogoutError]: {
    priority: "high",
    title: "Authentication Logout",
    message: "Failed to logout",
    type: "error",
    duration: 5000,
    isRemovableByClick: true,
  },
  [ToastKey.AvatarUploadError]: {
    priority: "low",
    title: "Media Upload",
    type: "error",
    message: "Error uploading avatar.",
    duration: -1,
    isRemovableByClick: true,
  },
  [ToastKey.AvatarUploadSuccess]: {
    priority: "low",
    title: "Media Upload",
    type: "success",
    message: "Avatar Uploaded!",
    duration: 2000,
    isRemovableByClick: true,
  },
  [ToastKey.AvatarDeleteError]: {
    priority: "low",
    title: "Media Delete",
    type: "error",
    message: "Error deleting avatar.",
    duration: -1,
    isRemovableByClick: true,
  },
  [ToastKey.AvatarDeleteSuccess]: {
    priority: "low",
    title: "Media Delete",
    type: "success",
    message: "Avatar Deleted!",
    duration: 2000,
    isRemovableByClick: true,
  },
  [ToastKey.CreateRepositoryError]: {
    priority: "high",
    title: "Repository",
    message: "Error creating repository.",
    type: "error",
    duration: -1,
    isRemovableByClick: true,
  },
  [ToastKey.CreateRepositorySuccess]: {
    priority: "high",
    title: "Repository",
    message: `Repository created!`,
    type: "success",
    duration: 5000,
    isRemovableByClick: false,
  },
  [ToastKey.AuthenticatedUserError]: {
    priority: "low",
    title: "Authentication Flow",
    message: "Error getting authenticated user.",
    type: "error",
    duration: 5000,
    isRemovableByClick: true,
  },
  [ToastKey.AuthSignatureError]: {
    priority: "low",
    title: "Authentication Flow",
    message: "Error creating auth signature.",
    type: "error",
    duration: 5000,
    isRemovableByClick: true,
  },
  [ToastKey.UpdateUserOnboardingError]: {
    priority: "low",
    title: "User Flow",
    type: "error",
    message: "Error onboarding user",
    duration: -1,
    isRemovableByClick: true,
  },
  [ToastKey.UpdateUserOnboardingSuccess]: {
    priority: "low",
    title: "User Flow",
    type: "success",
    message: "Success onboarding user",
    duration: 2000,
    isRemovableByClick: true,
  },
  [ToastKey.ResizeAvatar]: {
    priority: "low",
    title: "Media Resize",
    type: "info",
    message: "Resizing avatar...",
    duration: -1,
    isRemovableByClick: true,
  },
  [ToastKey.CreateRecordError]: {
    priority: "high",
    title: "Record",
    message: "Error creating record.",
    type: "error",
    duration: -1,
    isRemovableByClick: true,
  },
  [ToastKey.CreateRecordSuccess]: {
    priority: "high",
    title: "Record",
    message: `Record created!`,
    type: "success",
    duration: 5000,
    isRemovableByClick: false,
  },
  [ToastKey.CreateCommitError]: {
    priority: "high",
    title: "Commit",
    message: "Error creating commit.",
    type: "error",
    duration: -1,
    isRemovableByClick: true,
  },
  [ToastKey.CreateCommitSuccess]: {
    priority: "high",
    title: "Commit",
    message: `Commit created!`,
    type: "success",
    duration: 5000,
    isRemovableByClick: false,
  },
  [ToastKey.GetUniversalRecordMetaError]: {
    priority: "high",
    title: "Record Meta",
    message: "Error getting record meta.",
    type: "error",
    duration: -1,
    isRemovableByClick: true,
  },
};
