pub mod user;
pub mod artist_profile;
mod record;
mod checkpoint;
mod media;
mod media_record;
mod media_checkpoint;
mod musician_repertoire;
mod musician_repertoire_record;
pub mod commands;
pub mod auth;